#!/bin/sh

declare -a apps=(
"org.mozilla.firefox"
"org.videolan.VLC"
"com.microsoft.Edge"
"com.discordapp.Discord"
"com.mattjakeman.ExtensionManager"
"org.gimp.GIMP"
"org.libreoffice.LibreOffice"
"org.gnome.DejaDup"
"org.gustavoperedo.FontDownloader"
"com.github.tchx84.Flatseal"
"net.cozic.joplin_desktop"
"com.transmissionbt.Transmission"
"org.gnome.Builder"
)

# Workaround for some packages I havent figured how to build with buildah yet (using Containerfile)
declare -a pkgs=(
"ufw"
"virt-install"
"libvirt-daemon-config-network"
"libvirt-daemon-kvm"
"qemu-kvm"
"virt-manager"
"virt-viewer"
"virt-top"
)


if test -e "$HOME"/.config/ublue/firstboot-done; then
    echo "Already ran"
    exit 0
fi

(
echo "# Waiting for Internet connection"
until /usr/bin/ping -q -c 1 flathub.org; do sleep 1; done
echo "00"

echo "# Removing Filtered Flathub Repository"
/usr/bin/flatpak remote-delete flathub --force ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing Filtered Flathub Repo Failed"
        exit 1
fi
echo "3"

echo "# Enabling Flathub Repository"
/usr/bin/flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Adding Flathub Repo Failed"
        exit 1
fi
echo "5"

echo "# Replacing Fedora Flatpaks with Flathub Ones (this may take a while)"
/usr/bin/flatpak install --user --noninteractive org.gnome.Platform//43
/usr/bin/flatpak install --user --noninteractive --reinstall flathub $(flatpak list --app-runtime=org.fedoraproject.Platform --columns=application | tail -n +1 )
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Replacing Fedora Flatpaks Failed"
        exit 1
fi
echo "20"

echo "Removing all preinstalled Flatpaks"
/usr/bin/flatpak remove --system --noninteractive --all ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing all preinstalled flatpaks failed"
        exit 1
fi

echo "# Removing Fedora Flatpak Repository"
/usr/bin/flatpak remote-delete fedora --force ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing Fedora Flatpak Repo Failed"
        exit 1
fi
echo "25"

for app in "${!apps[@]}"
do
  echo "# Installing ${apps[$app]}"
  /usr/bin/flatpak install --user --noninteractive flathub ${apps[$app]}
  if [ "$?" != 0 ] ; then
          zenity --error \
            --text="Installing ${apps[$app]} Failed"
          exit 1
  fi
  echo $app ${apps[$app]} 
done

echo "# Installing $pkgs"
/usr/bin/rpm-ostree install ${pkgs[@]}
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing $pkgs Failed"
        exit 1
fi

echo "# Reticulating Final Splines"
mkdir -p "$HOME"/.config/ublue/
touch "$HOME"/.config/ublue/firstboot-done

) | 
     
   zenity --progress --title="uBlue Desktop Firstboot" --percentage=0 --auto-close --no-cancel --width=300

if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Firstboot Configuration Error"
fi
